name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Проверка кода из репозитория
        uses: actions/checkout@v3

      - name: Запуск Semgrep для статического анализа кода
        uses: returntocorp/semgrep-action@v2.36.1
        with:
          config: 'p/r2c'

      - name: Установка Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Логин в Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Сборка Docker образа
        id: build
        uses: docker/build-push-action@v4
        with:
          context: .
          push: false
          tags: melnik887/api_calculator:latest

      - name: Сканирование Docker образа с Trivy
        uses: aquasecurity/trivy-action@v0.30.1
        with:
          image-ref: melnik887/api_calculator:latest
          format: 'table'
          exit-code: '0'

      - name: Пуш Docker образа
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: melnik887/api_calculator:latest

      - name: Деплой на сервер (опционально)
        run: echo "Деплой не настроен"
