
name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Проверка кода из репозитория
      uses: actions/checkout@v3

    - name: Установка Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Логин в Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}

    - name: Сборка и пуш Docker образа
      uses: docker/build-push-action@v4
      with:
        context: .
        push: true
        tags: melnik887/api_calculator:latest

    - name: Деплой на сервер (опционально)
      run: echo "Деплой не настроен"