name: CI/CD Pipeline

# Права доступа для пайплайна
permissions:
  contents: write

# Триггер: запускать пайплайн при пуше в ветку main
on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Шаг 1: Проверка кода из репозитория
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          persist-credentials: true

      # Шаг 2: Настройка Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      # Шаг 3: Установка зависимостей
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r app/requirements.txt

      # Шаг 4: Запуск Semgrep для статического анализа кода (v1)
      - name: Run Semgrep for Static Code Analysis
        uses: returntocorp/semgrep-action@v1
        with:
          config: p/python

      # Шаг 5: Сборка Docker-образа
      - name: Build Docker image
        run: |
          docker build -t melnik887/api_calculator:${{ github.run_number }}.${{ github.run_id }} .

      # Шаг 6: Запуск Trivy для сканирования Docker-образа на наличие уязвимостей (0.29.0)
      - name: Run Trivy scan on Docker image
        uses: aquasecurity/trivy-action@v0.28.0
        with:
          image-ref: melnik887/api_calculator:${{ github.run_number }}.${{ github.run_id }}
          format: 'table'
          severity: 'CRITICAL,HIGH'

      # Шаг 7: Вход в Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      # Шаг 8: Пуш Docker-образа с версионным тегом и latest
      - name: Push Docker image with version tag
        run: |
          docker push melnik887/api_calculator:${{ github.run_number }}.${{ github.run_id }}
          docker tag melnik887/api_calculator:${{ github.run_number }}.${{ github.run_id }} melnik887/api_calculator:latest
          docker push melnik887/api_calculator:latest
